# Generated by Django 3.1 on 2020-08-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('head0', models.CharField(max_length=500)),
                ('head1', models.CharField(max_length=3000)),
                ('head2', models.CharField(max_length=3000)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
